# Generated by Django 6.1 on 2026-09-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
