# Generated by Django 6.1 on 2026-09-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_comments_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
